package tpl

var ServerTpl string = `// Code generated by Kitex {{.Version}}. DO NOT EDIT.
package {{ToLower .ServiceName}}

import (
	{{- range $path, $aliases := .Imports}}
		{{- if not $aliases}}
			"{{$path}}"
		{{- else}}
			{{- range $alias, $is := $aliases}}
				{{$alias}} "{{$path}}"
			{{- end}}
		{{- end}}
	{{- end}}
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler {{call .ServiceTypeName}}, opts ...server.Option) server.Server {
    var options []server.Option
    {{template "@server.go-NewServer-option" .}}
    options = append(options, opts...)
	{{- if or (eq $.Codec "thrift") .StreamX}}
	options = append(options, server.WithCompatibleMiddlewareForUnary())
	{{- end}}

    svr := server.NewServer(options...)
    if err := svr.RegisterService(serviceInfo(), handler); err != nil {
            panic(err)
    }
	{{- if .FrugalPretouch}}
	pretouch()
	{{- end}}{{/* if .FrugalPretouch */}}
    return svr
}
{{template "@server.go-EOF" .}}

func RegisterService(svr server.Server, handler {{call .ServiceTypeName}}, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
`
