package consts

const (
	CtxKeyMethod = "K_METHOD"
	CtxKeyLogID  = "K_LOGID"
)

const (
	SERVICE_INLINE_RPCINFO_KEY    = "SERVICE_INLINE_RPCINFO_KEY"
	SERVICE_INLINE_SERVICE_NAME   = "SERVICE_INLINE_SERVICE_NAME"
	SERVICE_INLINE_DATA_KEY       = "SERVICE_INLINE_DATA_KEY"
	SERVICE_INLINE_CUSTOM_CTX_KEY = "SERVICE_INLINE_CUSTOM_CTX_KEY"
)
